from __future__ import annotations
import alphazero.engine
__all__ = ['OthelloBoard']
class OthelloBoard(alphazero.engine.Board):
    def __init__(self) -> None:
        ...
    def make_move(self, arg0: alphazero.engine.Color, arg1: alphazero.engine.Position) -> None:
        ...
    def player_corners(self, arg0: alphazero.engine.Color) -> int:
        ...
    def player_edges(self, arg0: alphazero.engine.Color) -> int:
        ...
    def player_frontier(self, arg0: alphazero.engine.Color) -> int:
        ...
    def player_interior(self, arg0: alphazero.engine.Color) -> int:
        ...
    def score(self, arg0: alphazero.engine.Color) -> int:
        ...
    def valid_moves(self, arg0: alphazero.engine.Color) -> alphazero.engine.Position:
        ...
